name: Render documents

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  render_document:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fgregg/knoxville_utility_burden/kub:1.0.1
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: make install/R
      - name: build report
        env:
          CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
        run: make
      - name: setup directory
        run: |
          mkdir public
          mv reports/*.pdf public
      - name: Github Pages Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./public