name: Render documents

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  render_document:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse
    steps:
      - name: install
        run: make install/R
