name: Render documents

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  render_document:
    runs-on: ubuntu-latest
    container:
      image: rocker/verse
      volumes: 
        - ${{ github.workspace }}:/workspace      
    steps:
      - uses: actions/checkout@v2
      - name: install system dependencies
        run: sudo apt-get update && sudo apt-get install libudunits2-dev libgdal-dev -y
      - name: install
        run: make install/R
      - name: build report
        env:
          CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
        run: make
